const commands = [
	'git checkout -b dev',
	'git commit -m "first commit" ',
	'sudo apt install steam',
	'sudo apt update',
	'rm -rf /*',
	'sudo apt install vim',
	'vim ./helloworld.c',
	'npx create-react-app reddit-clone',
	'rev "taco cat"',
	'rev "stressed desserts"',
	'rm final-really-final(3).docx',
	'cd src/lib/time/',
	'sudo chown rez:rez super_secret.txt',
	'df -h -x squashfs',
	'dd if=/dev/vda bs=4M conv=sparse',
	'gcc -g -o out helloworld.c sum.c',
	'gdb helloworld',
	'echo "1. buy milk:" > list.txt',
	'find . -size +10M -type f',
	'yes | npm init',
	'man vim',
	"sudo sh -c 'apt-get update && apt-get upgrade'",
	'vim -x myconfession.txt',
	'telnet towel.blinkenlights.nl',
	'ls -alv',
	'du -ah',
	'which python',
	'cp -rp lib src',
	'cp todo_list.txt todo_list.bak',
	'less dune.txt',
	'xxd flag.out',
	'python3 -c "while True: print(\'i love u\')"',
	'python3 -q app.py',
	'node app.js',
	'npm run debug',
	'view do_not_edit.txt',
	'ssh rez@172.12.12.0 -p 22',
	'ssh -vvv rez@nasa.com',
	'sudo vim /etc/ssh/sshd_config',
	'sudo service ssh status',
	'transmission-remote -l',
	'transmission-remote -t 1 -r',
	'cd ~',
	'date -d now',
	'cp -rp *.txt stuff',
	'mkdir texts | mv *.txt texts',
];

export default commands;
